using Design.IS7.Infrastructure.MongoDB.Collections.Social.AccountCollection.PublishOptions;
using MongoDB.Bson.Serialization.Attributes;

namespace Design.IS7.Infrastructure.MongoDB.Collections.Social.AccountCollection.Profile
{
    [BsonIgnoreExtraElements]
    public class ProfileDocument
    {
        public bool? ServerRender { get; set; }
        public bool? OuterQuotes { get; set; }
        public bool? HideUpperMoldings { get; set; }
        public bool? HideMoldings { get; set; }
        public bool? Quotes { get; set; }
        public bool? LooseQuote { get; set; }
        public bool? Text { get; set; }
        public bool? FloorPlanPrint { get; set; }
        public bool? PrintWithFooter { get; set; }
        public bool? VirtualReality { get; set; }
        public bool? PhotoRendering { get; set; }
        public bool? Markup { get; set; }
        public bool? ManageContent { get; set; }
        public bool? Impersonate { get; set; }
        public bool? ShowSpecSellerInfo { get; set; }
        public bool? UseMooblePrices { get; set; }
        public bool? ShowSignPremiumCard { get; set; }
        public bool? ShowUnavailableBrands { get; set; }
        public bool? ShowChangeAccountTypeOption { get; set; }
        public bool? ExportUsers { get; set; }
        public bool? ExportStores { get; set; }
        public bool? ManagePriceTables { get; set; }
        public bool? ManageStores { get; set; }
        public bool? CatalogPublish { get; set; }
        public int? CatalogPublishMonthlyLimit { get; set; }
        public bool? ShowBrandTags { get; set; }
        public bool? ShowPrivateSpecs { get; set; }
        public bool? PartnershipPaymentControl { get; set; }
        public bool? SubscriptionReport { get; set; }
        public bool? SetManualPrices { get; set; }
        public bool? PrivateProject { get; set; }
        public bool? RegisteredUsersReport { get; set; }
        public bool? Deploy { get; set; }
        public bool? PlannerModuleGroups { get; set; }
        public bool? Budgets { get; set; }
        public int? BudgetType { get; set; }
        public BudgetProfileItemDocument? BuyOnline { get; set; }
        public BudgetProfileItemDocument? FindStore { get; set; }
        public BudgetProfileItemDocument? ItemsList { get; set; }
        public BudgetProfileItemDocument? MakeBudget { get; set; }
        public BudgetProfileItemDocument? MakeOrder { get; set; }
        public bool? ShowHiveColors { get; set; }
        public bool? SendBudgetToPartnership { get; set; }
        public bool? SendBccBudgetToPartnership { get; set; }
        public bool? ManageRepresentatives { get; set; }
        public bool? DirectSale { get; set; }
        public bool? RemoteShare { get; set; }
        public bool? Snapshots { get; set; }
        public int? AllowedSubscriptionTypes { get; set; }
        public bool? CanSubscribe { get; set; }
        public bool? Analytics { get; set; }
        public bool? AccessStatistics { get; set; }
        public bool? ReferencesWithoutEanReport { get; set; }
        public bool? EanWithoutSkuReport { get; set; }
        public bool? SkuWithoutReferenceReport { get; set; }
        public bool? BudgetSettings { get; set; }
        public bool? WatermarkSettings { get; set; }
        public bool? UnlimitedProjects { get; set; }
        public bool? SeeGroupedBudgetRequests { get; set; }
        public bool? BlockValidation { get; set; }
        public bool? ForceLogin { get; set; }
        public bool? RegisterNeedsApproval { get; set; }
        public bool? EditTops { get; set; }
        public bool? RedirectToEcommerceNotFoundStores { get; set; }
        public bool? CreateArrangement { get; set; }
        public bool? LightProfile { get; set; }
        public bool? ChangeMeasureUnit { get; set; }
        public int? MeasureUnit { get; set; }
        public bool? SeeElevation { get; set; }
        public bool? LowerWall { get; set; }
        public bool? Revest { get; set; }
        public bool? ChangeIndividualWallHeight { get; set; }
        public bool? LayoutLevels { get; set; }
        public bool? Layers { get; set; }
        public bool? Rotation { get; set; }
        public bool? Position { get; set; }
        public bool? InputHiveColorsRGB { get; set; }
        public bool? SeeRulers { get; set; }
        public bool? ChangeMoobleDesignInterface { get; set; }
        public bool? MoobleDesignInterface { get; set; }
        public bool? HideReferences { get; set; }
        public bool? UserControl { get; set; }
        public bool? EditProfile { get; set; }
        public bool? Subscription { get; set; }
        public bool? Showroom { get; set; }
        public bool? ChangeStrongCollision { get; set; }
        public bool? StrongCollision { get; set; }
        public string ShowAllRulers { get; set; }
        public bool? CreateGeometry { get; set; }
        public bool? EditItemGeneric { get; set; }
        public bool? HideMoobleDesignSubscription { get; set; }
        public string HeaderView { get; set; }
        public bool? ContactADesigner { get; set; }
        public string FeedbackEmail { get; set; }
        public bool? LoginPromob { get; set; }
        public bool? SendToCustomer { get; set; }
        public bool? Reports { get; set; }
        public bool? IdentificationTypeEditProfile { get; set; }
        public bool? TypeAccountEditProfile { get; set; }
        public bool? PhoneUS { get; set; }
        public bool? AddressUS { get; set; }
        public bool? ImportDxf { get; set; }
        public bool? ExportProjectDxf { get; set; }
        public bool? UnavailableProductWarning { get; set; }
        public bool? ShowUnavailableProducts { get; set; }
        public bool? EditAngles { get; set; }
        public bool? ShowroomEditor { get; set; }
        public bool? CanBuyCredits { get; set; }
        public CatalogPublishOptionsDocument CatalogPublishOptions { get; set; }
        public int? BudgetCsvLayout { get; set; }
        public bool? Render3DE { get; set; }
        public List<CustomButtonInfoDocument> PlannerCustomButtons { get; set; }
    }
}